### ISSUE TITLE
Malformed JSON in multipipeCreate event

### ISSUE THREAD

**Issue by adeelraza** [APE-Project/APE_Server#11]
multipipeCreate event returns a MALFORMED JSON which causes JSON.parse on line 180 of Core.js to fail. It's because after the CHANNEL raw data... if there are other events like JOIN LEFT or DATA, then instead of a comma the json is formed like ....}][{"time":"1289577226","raw":"DATA",.... Notice the ][. There should be a , instead of that.

QUICK FIX
Put this before line 180 to fix it till a proper server side fix is released:

raws = raws.replace(/][/gi,",");

**Comment by paraboul** [comment]
Thanks for the report. luckily I had the same bug yersterday that I can easily reproduce.
This can happen on slow client or huge data for me. Did you experience this bug on same situation ?

**Comment by adeelraza** [comment]
Yes. It happens when either there is a lot of activity going on in the channel and huge list of users. So by the time it sends the list of users, there are new messages appended with improper JSON.
