### ISSUE TITLE
Crashes when connecting to MySQL

### ISSUE THREAD

**Issue by Minike** [APE-Project/APE_Server#15]
/aped: symbol lookup error: ../modules/lib/libmod_spidermonkey.so: undefined symbol: scramble

**Comment by jacobbogers** [comment]
I got recent fork from github, it doesnt compile against the lates ubuntu 11 release bundled mysql client 

Did a workaround in build.sh

On line 37 , I replaced the If bash evaluation with a 1 -eq 2 (always false) so,..

#if [ -e "/usr/include/mysql/mysql.h" ]
if [ "1" -eq "2" ]

Then it will compile without  the mysql client lib,...,

**Comment by sadtaco** [comment]
I'm getting this same issue in Ubuntu 11.

**Comment by jacobbogers** [comment]
sadtaco,.., if you know how to compile it on ubuntu11 let me know. I didnt spend anymore time on this issue as i moved more to nodejs

**Comment by lcharette** [comment]
Issue over 2 years old. Closing. Reopen a new one if issue is still there.
