### ISSUE TITLE
Ape.log does not log when running in foreground

### ISSUE THREAD

**Issue by sebnow** [APE-Project/APE_Server#16]
APE should log to the file specified in the configuration file regardless of running mode (daemon of foreground). I'm trying to use upstart to supervise the aped process. Upstart doesn't play well with daemons that fork, so I want to set daemon = no, which works fine, however Ape.log logging stops working, even though logging from the core server still works. There's [no good way of  logging stdout to a file in upstart](http://serverfault.com/questions/114052/logging-a-daemons-output-with-upstart) (especially since ape.log is already being written to by the server).

Replication:
1. Use Ape.log in a server side JS module,
2. Set daemon = yes in the config and restart -> logging works,
3. Set daemon = no in the config and restart -> logging doesn't work.

**Comment by brunoc** [comment]
Looks like \n gets added when in daemon mode and not in console mode (adding \n to the Ape.log statement works) for ex: Ape.log("Bonjour") would not show up in console mode but Ape.log("Bonjour\n") does.

**Comment by lcharette** [comment]
Issue over a years old. Closing. Reopen a new one if issue is still there.
