### ISSUE TITLE
Http.js bugged?

### ISSUE THREAD

**Issue by paooolino** [APE-Project/APE_Server#17]
Examples like

Exemple 1:
    // URL to call
    var request = new Http('http://www.google.fr/');
    request.getContent(function(result) {
        Ape.log(result);
    });

don't work to me.
It seems the request is created but it never enters the getContent block. No errors returned. I couldn't find any useful information. Tried to use the last Http.js from github but the problem is not solved.

Thanks

**Comment by paraboul** [comment]
Hey,

What version? Last git?

**Comment by paooolino** [comment]
Server version: 1.1.2-dev
Build: Sep 8 2011

APE JSF Version: downloaded few days ago from website download page (assuming it's 1.1.0)
Http.js file has last modified date on Aug 25 2011 00:05

I tried also with the last Http.js

I'm using Build/uncompressed/apeClientJS.js

My APE conf:
APE.Config.baseUrl = 'http://app.myDomain.com/APE_JSF'; //APE JSF 
APE.Config.domain = 'app.myDomain.com'; 
APE.Config.server = 'app.myDomain.com:6969'; //APE server URL 

Just tried this example

```
var request = new Http('http://www.google.fr/');
request.getContent(function(result) {
    Ape.log(result);
});
```

but never enters the getContent function.

thanks :-)

Edit: all is working properly, I'm communivating yet between client-server, storing variables on the server, sending raws and commands and so on. Just http requests don't work.

**Comment by paraboul** [comment]
The last github revision is not stable yet. I suggest you to try the last release (1.1.1).

I check that ASAP.

Thanks ;)

**Comment by paooolino** [comment]
with server version 1.0.0 it works!
thanks.

**Comment by brunoc** [comment]
I confirm I have the same issue when compiling 1.1.2 on Fedora 15, downloaded 1.1.1 generic binary which seems to work.  Hope 1.1.1 is as stable as 1.1.2 for the rest!
