### ISSUE TITLE
APE convert float to int values with inlinepush

### ISSUE THREAD

**Issue by egguy** [APE-Project/APE_Server#2]
When i use the inlinepush module the float values are converted to int value. 

ex:

send to the APE server using inline push:
[{"cmd": "inlinepush", "params": 
  {"raw": "ping", "password": "testpasswd", "data": 
        {"content": {"timestamp": 1264062569.54, "coord": 
                 {"y": 1.0957805, "x": 49.449257}}}, "channel": "*TEST"}}]
[{"time":"1264012321","raw":"pushed","data":{"value":"ok"}}]

X and Y became:
[{"time":"1264013251","raw":"ping","data":{"content":{"timestamp":1264063517,
     "coord":{"y":1,"x":48}
}}}]

**Comment by egguy** [comment]
The version used is the 1.0 binaries from the officiel website

**Comment by paraboul** [comment]
egguy, what version? 1.01dev or 1.0?

**Comment by egguy** [comment]
1.0 from the web site, not the dev

**Comment by paraboul** [comment]
Ok, confirmed. (btw, the issue tracker is http://ape-project.lighthouseapp.com/dashboard ;))
