### ISSUE TITLE
missing ) after argument list (w/JSONP transport method)

### ISSUE THREAD

**Issue by foxhound87** [APE-Project/APE_Server#21]
the error message "missing ) after argument list" appears when I send an inlinepush message enabling JSONP transport method

I modified the file "APE_Server/scripts/commands/inlinepush.js"
I do not know if this is the correct procedure:

adding:

params.data.message = escape(params.data.message); 

before:

chan.pipe.sendRaw(params.raw, params.data);

**Comment by kingster** [comment]
Hi

Thanks, your change fixed the issue, but in my jsfile i have to unescape it manually.

**Comment by lcharette** [comment]
Issue over a years old. Closing. Reopen a new one if issue is still there.
