### ISSUE TITLE
1.1.2 dev with MySQL does not work on Ubuntu

### ISSUE THREAD

**Issue by sadtaco** [APE-Project/APE_Server#25]
I believe I have all the libraries needed installed. 
Running build.sh first gave an error of "/usr/bin/ld: cannot find -lmysac"
Running it again worked.  It seems to compile fine since running "make" in modules/deps/mysac says "nothing to be done" or something to that effect.

When I try use Ape.MySQL it doesn't throw any error, but there is no onConnect() callback triggered.  No mysql queries work, either.

That is all using the latest git hub version built from source.
Using the deb package I get ""symbol lookup error: /usr/lib/ape/libmod_spidermonkey.so: undefined symbol: scramble" "

I can only get aped working with mysql using a really old version I had on my HD.  This old version, however, crashes every day.

**Comment by oferbar** [comment]
It looks like mysql support got broken after version 1.0 (or 1.0.8 as some sources claim).
This is a major regression, and basically prevents us from any upgrade, for example, to get web sockets support.
Anyway, APE 1.0 server works in production with mysql pretty well.
Any other version after that is totally broken, and no signs of help for a very long time.

**Comment by sadtaco** [comment]
When I start the one I have where mysql works it says "Version : 1.01dev" but it crashes every day or two, which is almost as major of an issue.
Is there one where both mysql works and it doesn't crash all the time?

**Comment by oferbar** [comment]
As I said above ver 1.0 works for us.

**Comment by sadtaco** [comment]
None of the versions on the website, or the latest git, work for me, which are above 1.0.  I'm a little confused by what you mean since 1.1.2 is higher.
I guess you mean that 1.0-1.0.8 work.  Any idea of where I can get 1.0.8?

**Comment by oferbar** [comment]
I see it is not on the web site any more, but we have an older copy on production.
Maybe the owner of the site can help you with it.

I don't know where you can get ver 1.0.8, I just read a post that it was working but the link was broken.

I currently working on getting mysql working for the latest 1.1.1.
If I'll succeed, I will post the solution.

Good luck

**Comment by sadtaco** [comment]
If you could upload your older version somewhere, that'd be awesome.  A fix for the newer one is also good, but of course that'd take longer.
I have 1.01 running, which like I said crashes every day.

**Comment by oferbar** [comment]
Hi,

Here's a link to a blog that explain how to setup APE on Ubuntu.
There's a link inside to APE 1.0 which seems to be working:

http://adilsoncarvalho.com.br/blog/installing-ape-on-ubuntu-server-10-10

Good luck!

**Comment by sadtaco** [comment]
ape-server : Depends: libmysqlclient15off (>= 5.0.27-1) but it is not installable

/edit I guess I can have both libmysqlclient15off and  libmysqlclient16 installed.

**Comment by sadtaco** [comment]
The user.left() command doesn't work in 1.0 :/

I really wish the new ape would work with Ubuntu.

**Comment by sadtaco** [comment]
Great.  I tried getting a new version to work, but it wouldn't. Then I tried to go back to 1.0 and now 1.0 is crashing.

**Comment by ptejada** [comment]
The last few commits claim to have fix Mysql issues, you guys should give it a try if you are still working with the server
