### ISSUE TITLE
documentation on ape-project.org site not working

### ISSUE THREAD

**Issue by steve-obrien** [APE-Project/APE_Server#26]
Hi guys i think the wiki has been hacked on ape-project.org.

If you go to this link:
http://www.ape-project.org/docs/client/core/ 

Then try to click on any of the method descriptions, such as "addEvent", or "join" etc, the browser times out.

Also I have noticed some strange and irrelevant links to places dotted around.

**Comment by efyx** [comment]
The docs should be fixed now.
