### ISSUE TITLE
start() core command - libape-chat

### ISSUE THREAD

**Issue by johannesgerer** [APE-Project/APE_Server#3]
http://www.ape-project.org/docs/client/core/start.html
says a nick is required if libape-chat is used. But the source of the server does not contain anything about libape-chat!
Why do I still get a BAD_PARAMS if i invoke start() without parameters?

**Comment by efyx** [comment]
Hi, 
it's an error in our docs, it's not libape-chat but nickname.js open scripts/main.ape.js and comment the line with nickname.js

Cheers
