### ISSUE TITLE
ape project wiki doesnt show anything

### ISSUE THREAD

**Issue by ra0o0f** [APE-Project/APE_Server#33]
hello

your ape-project website introduce your project so well but when i go to docs and wiki pages,,they redirect to the same page and show nothing

**Comment by lcharette** [comment]
The wiki has been down for some time now. You can always find the wiki on the Web Archive Service: http://archive.org/web/web.php

The documentation is still up: http://www.ape-project.org/docs/server/

**Comment by rwngallego** [comment]
Why don't you put that files in the http://www.ape-project.org/ page again? New users don't know about the link you have provided. Also, it is not well viewed in the community if that page went down and never come back. You could bring access to the community users to upload the content again. I'll do it pleased...

**Comment by lcharette** [comment]
I contacted Anthony, the project manager, a couple of weeks ago about this. There was some development and good news, but I'm still waiting for a reply right now.

**Comment by lcharette** [comment]
A new wiki and website has been put up : http://ape-project.org/wiki/index.php?page=Main+page
