### ISSUE TITLE
Single quotes should not be encoded

### ISSUE THREAD

**Issue by ptejada** [APE-Project/APE_Server#34]
The server responds with a JSON string with single quotes escaped when they should not be escaped

The changes on commit https://github.com/APE-Project/APE_Server/commit/88a75bddab6695e5c4d2da4bb43fb70c2cb019de should be reversed

**Comment by lcharette** [comment]
I looked at this the other day. The encoding is required for some transport but not for other transport. See : https://groups.google.com/forum/?fromgroups=#!topic/ape-project/YLHxPTKgm80

**Comment by lcharette** [comment]
Issue over a year old. Closing. Reopen a new one if issue is still there.
