### ISSUE TITLE
Mysql Prepared Statements 

### ISSUE THREAD

**Issue by johannesgerer** [APE-Project/APE_Server#4]
The APE server could immensely benefit from the use of so called mysql prepared statements. How can this be done?

Info:

For repeated execution of a SQL command, where only parameters change, the MySQL C API offeres a function that employs the binary protocol to pass the arguments and execute it, which is extremly fast compared to usual way,
because the query does not have to be parsed every time and parameters are send as binary data which is way more efficient!

http://dev.mysql.com/doc/refman/5.0/en/c-api-prepared-statements.html

**Comment by johannesgerer** [comment]
Now that I looked into the source I might change the ticket:

Implement the use of the MySAC function for prepared statements:

mysac_set_stmt_prepare
mysac_send_stmt_prepare
mysac_set_stmt_execute
mysac_send_stmt_execute

I could try to do it but need some startup support!

**Comment by psish** [comment]
Hi there,

Thanks for your interest in our software. Unfortunately we are not using the issue manager of GitHub.

Could you please use Lighthouse for bugtrack : http://ape-project.lighthouseapp.com
And our Google Group mailing list for discussions : http://groups.google.com/group/ape-project/

Thanks :-)
