### ISSUE TITLE
subuser object status

### ISSUE THREAD

**Issue by ptejada** [APE-Project/APE_Server#43]
I have not checked other versions, but on master the `subuser` object seems to be blank slate. None of the documented methods are defined.

``` js
Ape.registerCmd('foo', true, function(params, info) {
    info.subuser.sendRaw('bar', {'ok':'true'});
});
```

will generate the following error: `TypeError: info.subuser.sendRaw is not a function`

**Comment by lcharette** [comment]
[From https://github.com/ptejada/ApePubSub/issues/22]

I never used sessions before and therefor never saw the subuser object. I tried _V1.0_ (https://github.com/APE-Project/APE_Server/tags) and it's the same as the latest version. Not sure the subuser actually ever existed...

**Comment by ptejada** [comment]
The following lines confirm `info.user` is an object of type subuser but none of the document methods are available as if is corrupted:

``` js
Ape.registerCmd('foo', true, function(params, info) {
    var toString = Object.prototype.toString;
    Ape.log(toString.call(infos.subuser));
});
```

Outputs `[object subuser]` which is inherited from the `Ape.subuser`

**Comment by lcharette** [comment]
Hum, we may need more info from @paraboul on this one.
