### ISSUE TITLE
socket.onRead  cannot triggered

### ISSUE THREAD

**Issue by zgysc** [APE-Project/APE_Server#59]
I write a script named “test.js” ，I put it to "example" directory so that it can be included when APE server start up.  And then, I write a TCP socket program by using netty, it listen port 6666 on the same host.  I can recieve message from netty program by using telenet.    however, test.js can only trigger onConnect and onDisconnect event.    I was wondering why onRead can not be triggered

Here is my script below:

var socket = new Ape.sockClient(6666, "127.0.0.1", {flushlf: true});
socket.onConnect = function(){
        Ape.log("we are connected!");
        socket.write("ape");
}
socket.onRead = function(data){
        Ape.log("yes");
}
socket.onDisconnect = function(data){
Ape.log("Gone!");
}

**Comment by lcharette** [comment]
I think that to trigger, onRead need to see an end of line character ("/n") if you send something from the command line (or putty).

**Comment by zgysc** [comment]
oh,yes!  Thank you

**Comment by zgysc** [comment]
by the way,  How can I do the performance test?  did you ever test it?  the best concurrent number is ?
