### ISSUE TITLE
Server "crash" on chat demo multi-tab

### ISSUE THREAD

**Issue by mrbrdo** [APE-Project/APE_Server#7]
To replicate:
Open the Chat demo app in Firefox in one tab. Then open it in another tab. Firebug shows repeated (fast) requests to server and page is left blank... If this tab is closed and the first tab is reloaded it has the same bug now. Must restart server for it to work again...

**Comment by mrbrdo** [comment]
Note: in chrome it seems this problem is not triggered. Also after doing this in Firefox it will still work in Chrome so I guess this is a client problem.

**Comment by paraboul** [comment]
Hi,

Are you using the last git trunk ?

Thanks

**Comment by mrbrdo** [comment]
No i downloaded from the index page.

**Comment by paraboul** [comment]
Ok, can you please try the git version (run sh build.sh in order to build it), and tell me if the bug still happen ?

Thanks

**Comment by lcharette** [comment]
Issue over 4 years old. Closing. Reopen a new one if issue is still there.
